In [58]:
import numpy as np
import pandas as pd
from matplotlib.font_manager import weight_dict

s1 = pd.Series(np.arange(0,5,2),index=['a','b','c'])

s1
# index 下标
# values 值
# 键值对

a    0
b    2
c    4
dtype: int64

In [59]:
cities = ['Kolkata', 'Chicago', 'Toronto', 'Lisbon']
populations = [14.85, 2.71, 2.93, 0.51]
city_series = pd.Series(populations, index=cities)
city_series

Kolkata    14.85
Chicago     2.71
Toronto     2.93
Lisbon      0.51
dtype: float64

In [60]:
city_series.index #属性

Index(['Kolkata', 'Chicago', 'Toronto', 'Lisbon'], dtype='object')

In [61]:
city_series.values #属性

array([14.85,  2.71,  2.93,  0.51])

In [62]:
s2 = pd.Series(25,index=['a','b','c'])
s2

a    25
b    25
c    25
dtype: int64

In [63]:
dict1={'Alice':'2341','Beth':'9102','Cecil':'3258'}
sd=pd.Series(dict1)
sd

Alice    2341
Beth     9102
Cecil    3258
dtype: object

In [64]:
s3 = pd.Series(data=[90,86,95],index=['Java','C','Python'])
s3

Java      90
C         86
Python    95
dtype: int64

In [65]:
s3['C']

np.int64(86)

In [66]:
s3[1]

C:\Users\24138\AppData\Local\Temp\ipykernel_48424\3948023335.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s3[1]

np.int64(86)

In [67]:
s3.C

np.int64(86)

In [68]:
s3[0:2] #0 1 2(取不到)

Java    90
C       86
dtype: int64

In [69]:
s3[['Python','Java']]

Python    95
Java      90
dtype: int64

In [70]:
s3[s3>=90]

Java      90
Python    95
dtype: int64

In [71]:
s3['C'] = 96
s3

Java      90
C         96
Python    95
dtype: int64

In [72]:
s4 = pd.Series(data=[90,86,np.nan,95], index=['Java','C','Scala', 'Python'])

s4

Java      90.0
C         86.0
Scala      NaN
Python    95.0
dtype: float64

In [73]:
s4.sum()

np.float64(271.0)

In [74]:
s4.var()

np.float64(20.333333333333332)

In [75]:
data = {'C':[86,90,87,95],
        'Python':[92,89,89,96],
        'DataMining': [90,91,89,86]
        }
studentDF = pd.DataFrame(data, index=['LiQian','WangLi','YangXue', 'LiuTao'])
studentDF

          C  Python  DataMining
LiQian   86      92          90
WangLi   90      89          91
YangXue  87      89          89
LiuTao   95      96          86

In [76]:
studentDF = pd.DataFrame(data, columns=['C','Python'])
studentDF

    C  Python
0  86      92
1  90      89
2  87      89
3  95      96

In [77]:
data_dict = {
    "name":{'one':"Jack",'two':"Mary",'three':"John",'four':"Alice"},
    "age":{'one':10,'two':20,'three':30,'four':40},
    "weight":{'one':30,'two':40,'three':50,'four':65}
}
df2 = pd.DataFrame(data_dict)
#       name age weight
#one    jack
#two    mary
#three  john
#four   alice
df2

        name  age  weight
one     Jack   10      30
two     Mary   20      40
three   John   30      50
four   Alice   40      65

In [78]:
studentDF = pd.DataFrame(#data
    [[78,82,93],[85,86,97],[90,92,81]],
             ['zhangsan','lisi', 'wangwu'],#index
             ['python','java', 'c'])# column)
studentDF

          python  java   c
zhangsan      78    82  93
lisi          85    86  97
wangwu        90    92  81

In [79]:
studentDF['python']

zhangsan    78
lisi        85
wangwu      90
Name: python, dtype: int64

In [80]:
result = studentDF.loc[["zhangsan","lisi"]]
result

          python  java   c
zhangsan      78    82  93
lisi          85    86  97

In [81]:
result = studentDF.iloc[0:3,:3]
result

          python  java   c
zhangsan      78    82  93
lisi          85    86  97
wangwu        90    92  81

In [82]:
import pandas as pd
data={"name":["Jack","Mary","John","Alice"],
    "age":[10,20,30,40],
    "weight":[30,40,55,65]}
df=pd.DataFrame(data)
df

    name  age  weight
0   Jack   10      30
1   Mary   20      40
2   John   30      55
3  Alice   40      65

In [84]:
df_new =df.drop(labels=0,axis=0)
df_new

    name  age  weight
1   Mary   20      40
2   John   30      55
3  Alice   40      65