In [3]:
import numpy as np
import pandas as pd
# index属性必须和data数据长度一致
s1 = pd.Series(np.arange(0,5,2),index=['a','b','c'])
s1

a    0
b    2
c    4
dtype: int64

In [4]:
s1.values

array([0, 2, 4])

In [5]:
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [6]:
s1.shape

(3,)

In [8]:
s2 = pd.Series(25,index=['a','b','c','d','e'])
s2

a    25
b    25
c    25
d    25
e    25
dtype: int64

In [9]:
dict1 = {'Alice':25,'Bob':26,'Charlie':27}
sd = pd.Series(dict1)
sd

Alice      25
Bob        26
Charlie    27
dtype: int64

In [10]:
s3 = pd.Series(data=[90,86,95], index=['Java','C','Python'])
s3

Java      90
C         86
Python    95
dtype: int64

In [11]:
s3['C']

np.int64(86)

In [16]:
s3[2]

C:\Users\24138\AppData\Local\Temp\ipykernel_27336\398130320.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s3[2]

np.int64(95)

In [13]:
s3[0:2]

Java    90
C       86
dtype: int64

In [17]:
s3[['Python','C','Java']]

Python    95
C         86
Java      90
dtype: int64

In [18]:
s3[s3>90]

Python    95
dtype: int64

In [19]:
s3['C'] = 96
s3

Java      90
C         96
Python    95
dtype: int64

In [21]:
s3.name = 'grade'
s3.name

'grade'

In [24]:
s3.index.name = '科目'
s3.values
s3

科目
Java      90
C         96
Python    95
Name: grade, dtype: int64

In [25]:
s = pd.Series(data=[90,86,np.nan,95], index=['Java','C','Scala', 'Python'])
s.sum()

np.float64(271.0)

In [26]:
s.drop('Scala')

Java      90.0
C         86.0
Python    95.0
dtype: float64

In [28]:
s.dropna()

Java      90.0
C         86.0
Python    95.0
dtype: float64

In [29]:

# 2. Series 间运算
s5 = pd.Series([10,20], index=['c','d'])
s6 = pd.Series([2,4,6,8], index=['a','b','c','d'])

s5 + s6

a     NaN
b     NaN
c    16.0
d    28.0
dtype: float64

In [31]:
data = {'C':[86,90,87,95],'Python':[92,89,89,96],'DataMining': [90,91,89,86]}
studentDf = pd.DataFrame(data, index=['LiQian','WangLi','YangXue', 'LiuTao'])

studentDf

          C  Python  DataMining
LiQian   86      92          90
WangLi   90      89          91
YangXue  87      89          89
LiuTao   95      96          86

In [32]:
stu1 = pd.DataFrame(data, columns=['C','DataMining'])
stu1

    C  DataMining
0  86          90
1  90          91
2  87          89
3  95          86

In [34]:
data_read = {
    "name":["Jack","Mary","John","Alice"],
    "age":[10,20,30,40],
    "weight":[30,40,55,65]
}
df = pd.DataFrame(data_read)
df

    name  age  weight
0   Jack   10      30
1   Mary   20      40
2   John   30      55
3  Alice   40      65

In [37]:
df.drop(labels=0, axis=0)

    name  age  weight
1   Mary   20      40
2   John   30      55
3  Alice   40      65

In [41]:
df.drop(labels='weight',axis=1)

    name  age
0   Jack   10
1   Mary   20
2   John   30
3  Alice   40

In [42]:
df.drop(columns='weight')

    name  age
0   Jack   10
1   Mary   20
2   John   30
3  Alice   40

In [45]:
df

    name  weight
0   Jack      30
1   Mary      40
2   John      55
3  Alice      65