In [1]:
import pandas as pd
d = {"a":1,"b":2,"c":3}
ser = pd.Series(data=d,index=["a","b","c"])
ser

a    1
b    2
c    3
dtype: int64

In [2]:
d = {"a":1,"b":2,"c":3}
ser = pd.Series(data=d,index=["x","y","z"]) #不匹配
ser

x   NaN
y   NaN
z   NaN
dtype: float64

In [6]:
data={"C":[86,90,87,95],"Python":[92,89,89,96],"DataMining": [90,91,89,86]}
studentDF = pd.DataFrame(data, index=['LiQian','WangLi','YangXue', 'LiuTao'])
studentDF

          C  Python  DataMining
LiQian   86      92          90
WangLi   90      89          91
YangXue  87      89          89
LiuTao   95      96          86

In [9]:
re =  pd.DataFrame(studentDF,columns=["C","Python"])
re

          C  Python
LiQian   86      92
WangLi   90      89
YangXue  87      89
LiuTao   95      96

In [ ]:
pd.DataFrame([[78,82,93],[85,86,97],[90,92,81]],
             ['ZhangSan','LiHua','WangQiang'],['Python','Java','C'])

In [10]:
studentDF.values

array([[86, 92, 90],
       [90, 89, 91],
       [87, 89, 89],
       [95, 96, 86]])

In [12]:
studentDF['Python']

LiQian     92
WangLi     89
YangXue    89
LiuTao     96
Name: Python, dtype: int64

In [13]:
studentDF.loc['YangXue']

C             87
Python        89
DataMining    89
Name: YangXue, dtype: int64

In [16]:
df = pd.DataFrame(
    [[1,2],[4,5],[7,8]],
    index=['cobra','viper','sidewinder'],
    columns=['max_speed','shield']
)
df

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [17]:
df.loc["viper"]

max_speed    4
shield       5
Name: viper, dtype: int64