In [2]:
import pandas as pd
from pandas import DataFrame

csvframe= pd.read_csv('student.csv')

csvframe
type(csvframe)

pandas.core.frame.DataFrame

In [3]:
tableValue = pd.read_table('student.csv',sep=',')
tableValue

       Name  Math  Physics  Chemistry
0    WangLi    93       88         90
1  ZhangHua    97       86         92
2    LiMing    84       72         77
3   ZhouBin    97       94         80

In [4]:
headvalue = pd.read_csv('student.csv',header=[0,2])
headvalue

      Name Math Physics Chemistry
  ZhangHua   97      86        92
0   LiMing   84      72        77
1  ZhouBin   97      94        80

In [5]:
value = pd.read_csv('student.csv',usecols=[1,2])
value

   Math  Physics
0    93       88
1    97       86
2    84       72
3    97       94

In [7]:
value = pd.read_csv('student.csv',header=1,names=['name','maths','physical','chemistry'])
value

       name  maths  physical  chemistry
0  ZhangHua     97        86         92
1    LiMing     84        72         77
2   ZhouBin     97        94         80

In [8]:
value = pd.read_csv('student.csv',index_col=[0,1])
value

               Physics  Chemistry
Name     Math
WangLi   93         88         90
ZhangHua 97         86         92
LiMing   84         72         77
ZhouBin  97         94         80

In [15]:
import pandas as pd
data_range = pd.date_range(start="20180801",periods=4)
df=pd.DataFrame({'book':[12,13,15,22],'box':[3,8,13,18],'pen':[5,7,12,15]},index=data_range)


df.to_csv('bbp2.csv',index_label="timestamp")