In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



csvframe = pd.read_csv('student.csv')
csvframe

       Name  Math  Physics  Chemistry
0    WangLi    93       88         90
1  ZhangHua    97       86         92
2    LiMing    84       72         77
3   ZhouBin    97       94         80

In [4]:
type(csvframe)

pandas.core.frame.DataFrame

In [10]:
headerdemo = pd.read_csv('student.csv',header=[0,1,3])
headerdemo

      Name Math Physics Chemistry
    WangLi   93      88        90
    LiMing   84      72        77
0  ZhouBin   97      94        80

In [11]:
value = pd.read_table('1.txt')
value

  C  Python Java
0    1  4      5
1    3  3      4
2    4  2      3
3    2  1      1

In [13]:
value = pd.read_table('1.txt',sep='\s+',engine='python')
value

   C  Python  Java
0  1       4     5
1  3       3     4
2  4       2     3
3  2       1     1